export enum UserRole {
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  OHS_PRACTITIONER = 'OHS_PRACTITIONER',
  SECURITY_PRACTITIONER = 'SECURITY_PRACTITIONER',
  FINANCE_OFFICIAL = 'FINANCE_OFFICIAL',
  EMPLOYEE = 'EMPLOYEE',
}
