export enum UserRole {
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  OHS_PRACTITIONER = 'OHS_PRACTITIONER',
  FIRST_AIDER = 'FIRST_AIDER',
  HR = 'HR',
  FINANCE_OFFICIAL = 'FINANCE_OFFICIAL',
  EMPLOYEE = 'EMPLOYEE',
}
